FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project to ensure frontend can read config files if needed
COPY . .

ENV PORT=8501
EXPOSE $PORT

# Run the Streamlit application
CMD sh -c "streamlit run Frontend/app.py --server.port $PORT --server.address 0.0.0.0"
